server:
  port: 30001
  contextPath: /dainbow

security:
  sessions: ALWAYS

spring:
  session:
    store-type: redis

zuul:
  routes:
    login:
      url: http://localhost:30005/login
    auth:
      url: http://localhost:30005
      sensitive-headers:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:

logging:
  level:
    org.springframework.security: DEBUG
