server:
  port: 30005
  contextPath: /dainbow/accounter

security:
  oauth2:
    sso:
      loginPath: /oauth2
    client:
      clientId: 1069112770187-86kp601ddg7bt7m4kvf1s6pokmienrob.apps.googleusercontent.com
      clientSecret: tH-1KPwe3Q7LgXwdd_qVJTA_
      scope: https://www.googleapis.com/auth/plus.me
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
