server:
  port: 30005
  # contextPath: /dainbow/accounter

security:
  user:
    password: usersecret
  oauth2:
    client:
      client-id: inner
      client-secret: innersecret
      scope: read,write
      auto-approve-scopes: '.*'

oauth2:
  google:
    loginUrl: /login/google
    client:
      clientId: 1069112770187-86kp601ddg7bt7m4kvf1s6pokmienrob.apps.googleusercontent.com
      clientSecret: tH-1KPwe3Q7LgXwdd_qVJTA_
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      scope: https://www.googleapis.com/auth/userinfo.profile
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v1/userinfo?alt=json
